/**
 * OG cards for the standing pages.
 *
 * Posts get a card each from `src/pages/og/[slug].png.ts`. Everything else used
 * to fall back to one generic `/og/default.png`, so sharing /about and
 * /projects/factal produced identical previews. These give each standing page
 * its own card, generated by `src/pages/og/page/[slug].png.ts`.
 *
 * The title here is what appears large on the card. The card already carries
 * "Cory Bergman · corybe.com" above and the avatar and name below, so titles
 * should name the subject, not repeat the site.
 */
import { companies } from './companies';

const standing = [
	{ slug: 'about', title: 'About Cory Bergman' },
	{ slug: 'projects', title: 'Companies, writing and press' },
	{ slug: 'speaking', title: 'Speaking on AI and global security' },
	{ slug: 'topics', title: 'Every post by topic' },
];

/** Every card this endpoint generates: the standing pages plus one per company. */
export const pageCards: { slug: string; title: string }[] = [
	...standing,
	...companies.map((company) => ({ slug: company.slug, title: company.title })),
];

/**
 * Path to a standing page's card. Pass the result as `image` to BaseLayout.
 * Slugs come from `pageCards`; an unknown one would 404, so keep them in sync.
 */
export function pageCard(slug: string): string {
	return `/og/page/${slug}.png`;
}
